name: npm-publish

on:
  push:
    branches:
      - master

jobs:

  npm-publish:

    name: Publish to NPM
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@master
        with:
          ref: master

      - name: Check version changes
        uses: EndBug/version-check@v1
        id: check

      - name: Set up Node.js for NPM
        if: steps.check.outputs.changed == 'true'
        uses: actions/setup-node@v2
        with:
          registry-url: "https://registry.npmjs.org"

      - name: Publish package to NPM
        if: steps.check.outputs.changed == 'true'
        run: npm i --no-package-lock --no-save pnpm && npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
